"use strict";

/** Synthetic metric keys for kiosk / RMS alignment drills (portfolio demo only). */

const LABELS = Object.freeze([
  { id: "kiosk.queue.depth", tier: "lobby", desc: "Queue depth telemetry for kiosk sessions" },
  { id: "kiosk.pay.latency_ms", tier: "lobby", desc: "Payment hop latency rollup" },
  { id: "crs.rateplan.drift_pct", tier: "backoffice", desc: "CRS rate-plan drift sentinel" },
  { id: "hk.room.release_lag_min", tier: "service", desc: "HK release lag baseline" },
  { id: "audit.nightly.variance_pct", tier: "backoffice", desc: "Nightly variance guardrail" },
  { id: "pos.bridge.errors_5m", tier: "tower-a", desc: "POS bridge error density" },
  { id: "baggage.handoff_miss", tier: "lobby", desc: "Lost-and-found handoff omissions" },
  { id: "ivr.sla.answer_sec", tier: "service", desc: "Concierge SLA answer pacing" },
  { id: "mobile.key_failures", tier: "tower-b", desc: "Mobile key redemption failures" },
  { id: "energy.room.hvac_peak_kw", tier: "service", desc: "Peak HVAC telemetry per archetype bundle" },
  { id: "wifi.session.drop_pct", tier: "tower-a", desc: "Session drop sentinel for conferencing floors" },
  { id: "spa.waitlist.overflow", tier: "tower-b", desc: "Spa wait queue overflow sentinel" },
  { id: "valet.retrieve_p95_sec", tier: "lobby", desc: "Valet retrieval p95 pacing" },
  { id: "banquet.turn_buffer_min", tier: "service", desc: "Banquet churn buffer sentinel" },
  { id: "laundry.pressure_index", tier: "service", desc: "Laundry pressure rollup" },
  { id: "minibar.stockout_pct", tier: "tower-a", desc: "Minibar stock outage pacing" },
  { id: "complaint.cx.reopen_ratio", tier: "backoffice", desc: "CX ticket reopen sentinel" },
  { id: "security.keycard.recycle_cnt", tier: "tower-a", desc: "Keycard recycle sentinel" },
  { id: "engineering.elev_fault", tier: "service", desc: "Elevator fault escalation" },
  { id: "kitchen.expedite_lag_sec", tier: "service", desc: "In-room expedite pacing" },
  { id: "nightaudit.posting_miss", tier: "backoffice", desc: "Night audit tie-out sentinel" },
  { id: "deposit.hold_conflict", tier: "backoffice", desc: "Deposit hold conflict sentinel" },
  { id: "group.block.slippage_pct", tier: "backoffice", desc: "Group block pacing slippage" },
  { id: "forecast.pickup_miss", tier: "backoffice", desc: "Pickup forecast miss sentinel" },
  { id: "rate.parry_index", tier: "backoffice", desc: "Compset parry sentinel" },
  { id: "channel.commission_variance", tier: "backoffice", desc: "Channel commission sentinel" },
  { id: "ota.content_stale_hours", tier: "backoffice", desc: "OTA content freshness drift" },
  { id: "wholesaler.tax_mismatch", tier: "backoffice", desc: "Wholesale tax mismatch sentinel" },
  { id: "corporate.ld_pattern", tier: "backoffice", desc: "Corporate LOS pattern sentinel" },
  { id: "airline.crew_block_noise", tier: "tower-b", desc: "Crew-block noise sentinel" },
  { id: "tour.series_peaks", tier: "tower-b", desc: "Tour-bus peak sentinel" },
  { id: "conference.room_overrun_pct", tier: "tower-a", desc: "Conference overrun sentinel" },
  { id: "av.sync_delay_ms", tier: "tower-a", desc: "AV sync sentinel" },
  { id: "childcare.capacity_ratio", tier: "tower-b", desc: "Kids club capacity sentinel" },
  { id: "pool.chemical_variance", tier: "service", desc: "Pool chemical sentinel" },
  { id: "gym.equipment_fault", tier: "tower-a", desc: "Gym fault sentinel" },
  { id: "retail.impulse_miss", tier: "lobby", desc: "Retail impulse sentinel" },
  { id: "coffee.kiosk_throughput_cph", tier: "lobby", desc: "Coffee kiosk throughput" },
  { id: "parking.gate_retries", tier: "service", desc: "Parking gate retry sentinel" },
  { id: "shuttle.otp_variance_min", tier: "service", desc: "Shuttle OTP variance sentinel" },
  { id: "watercraft.waitlist_pressure", tier: "tower-b", desc: "Marina queue sentinel (synthetic demo)" },
  { id: "helipad.turnaround_min", tier: "tower-b", desc: "Helipad turnaround sentinel" },
  { id: "beekeeping.micro_apiary_hum_pct", tier: "service", desc: "Eco amenity sentinel (placeholder)" },
  { id: "api.version_skew_pct", tier: "backoffice", desc: "Client API skew sentinel" },
  { id: "cache.invalidate_storm", tier: "service", desc: "Cache churn sentinel" },
  { id: "queue.backpressure_lvl", tier: "service", desc: "Kafka-style backpressure sentinel" },
  { id: "cron.stuck_job_min", tier: "service", desc: "Stuck cron sentinel" },
  { id: "db.pool.wait_ms", tier: "service", desc: "DB pool wait sentinel" },
  { id: "trace.sample_drop_pct", tier: "service", desc: "Trace sampling drop sentinel" },
  { id: "edge.latency_budget_ms", tier: "tower-a", desc: "Edge latency budget sentinel" },
  { id: "cdn.stale_burst", tier: "service", desc: "CDN staleness sentinel" },
  { id: "sse.reconnect_ratio", tier: "lobby", desc: "SSE reconnect sentinel" },
  { id: "graphql.field_cost", tier: "service", desc: "Synthetic GraphQL hotspot sentinel" },
  { id: "grpc.retry_storm", tier: "service", desc: "gRPC retry sentinel" },
  { id: "mqtt.topic_noise", tier: "service", desc: "MQTT topic noise sentinel" },
  { id: "lambda.cold_start_ms", tier: "backoffice", desc: "Serverless cold start sentinel" },
  { id: "stepfn.stall_min", tier: "backoffice", desc: "Workflow stall sentinel" },
  { id: "s3.multipart_fail_pct", tier: "backoffice", desc: "Object storage multipart sentinel" },
  { id: "redis.eviction_pressure", tier: "service", desc: "Redis eviction sentinel" },
  { id: "postgres.seqscan_spike", tier: "service", desc: "Seq scan sentinel" },
  { id: "mysql.lock_wait_pct", tier: "service", desc: "Lock wait sentinel" },
  { id: "mongo.oplog_pressure", tier: "service", desc: "Oplog pressure sentinel" },
  { id: "elastic.query_latency_p95", tier: "backoffice", desc: "Search latency sentinel" },
  { id: "prometheusCardinality.burst", tier: "service", desc: "Metric cardinality sentinel" },
  { id: "slo.error_budget_remain_pct", tier: "service", desc: "SLO error budget sentinel" },
  { id: "canary.rollout_variance", tier: "service", desc: "Canary variance sentinel" },
  { id: "feature.flag_stale_reads", tier: "service", desc: "Feature flag staleness sentinel" },
  { id: "payments.auth_soft_decline_pct", tier: "lobby", desc: "Auth soft decline sentinel" },
  { id: "payments.capture_lag_hours", tier: "lobby", desc: "Capture lag sentinel" },
  { id: "fx.spread_variance_bps", tier: "backoffice", desc: "FX conversion sentinel" },
  { id: "tax.locale_mismatch_pct", tier: "backoffice", desc: "Locale tax sentinel" },
  { id: "deposit.chargeback_risk_pts", tier: "backoffice", desc: "Chargeback risk sentinel" },
  { id: "loyalty.points_drift", tier: "backoffice", desc: "Loyalty drift sentinel" },
  { id: "membership.tier_queue_depth", tier: "lobby", desc: "Membership queue sentinel" },
  { id: "upsell.attach_rate", tier: "lobby", desc: "Upsell attach sentinel" },
  { id: "spa.retail_attach_rate", tier: "tower-b", desc: "Spa retail attach sentinel" },
  { id: "minibar.restock_lag_h", tier: "tower-a", desc: "Minibar restock lag sentinel" },
  { id: "room.service.tray_lag_min", tier: "tower-a", desc: "Room service tray lag sentinel" },
  { id: "bellhop.dispatch_queue", tier: "lobby", desc: "Bellhop dispatch sentinel" },
  { id: "doorman.dwell_time_sec", tier: "lobby", desc: "Doorman dwell sentinel" },
  { id: "concierge.callback_miss_pct", tier: "lobby", desc: "Concierge callback sentinel" },
  { id: "vip.arrival_surprise_index", tier: "lobby", desc: "VIP arrival surprise sentinel" },
  { id: "porter.guest_ratio", tier: "lobby", desc: "Porter ratio sentinel" },
  { id: "housekeeping.cart_distance_km", tier: "service", desc: "HK cart travel sentinel" },
  { id: "linen.par_level_variance", tier: "service", desc: "Linen par variance sentinel" },
  { id: "turnover.inspection_fail_pct", tier: "service", desc: "Inspection fail sentinel" },
  { id: "deep_clean.cycle_slip_days", tier: "service", desc: "Deep clean slip sentinel" },
  { id: "pest.monitor_trigger", tier: "service", desc: "Pest sentinel" },
  { id: "hvac.zone_variance_c", tier: "tower-a", desc: "HVAC zoning sentinel" },
  { id: "lighting.scene_drift_pct", tier: "tower-b", desc: "Scene drift sentinel" },
  { id: "blinds.battery_health_pct", tier: "tower-b", desc: "Blinds battery sentinel" },
  { id: "safes.override_attempts", tier: "tower-a", desc: "Safe override sentinel" },
  { id: "cctv.blindspot_minutes", tier: "service", desc: "CCTV blind sentinel" },
  { id: "panic.button_latency_sec", tier: "service", desc: "Panic button latency sentinel" },
  { id: "fire.drill_ack_lag_sec", tier: "service", desc: "Drill acknowledgement sentinel" },
  { id: "water.pipe_pressure_var", tier: "service", desc: "Water pressure sentinel" },
  { id: "kitchen.grease_trap_cycle", tier: "service", desc: "Grease trap cycle sentinel" },
  { id: "barpour.variance_ml", tier: "lobby", desc: "Pour variance sentinel" },
  { id: "wine.temp_excursion_hours", tier: "tower-b", desc: "Wine temp excursion sentinel" },
  { id: "banquet.ice_melt_variance_kg", tier: "tower-a", desc: "Ice melt sentinel (synthetic demo)" },
  { id: "ballroom.partition_fault", tier: "tower-a", desc: "Partition fault sentinel" },
  { id: "stage.pin_load_kg", tier: "tower-a", desc: "Stage load sentinel" },
  { id: "crowd.audio_leak_db", tier: "tower-b", desc: "Audio leak sentinel" },
  { id: "pet.suite_amenity_miss", tier: "tower-b", desc: "Pet amenity miss sentinel" },
  { id: "plant.watering_miss", tier: "service", desc: "Green wall watering sentinel" },
  { id: "art.motion_trigger_noise", tier: "lobby", desc: "Art motion sentinel" },
  { id: "library.checkout_miss", tier: "tower-a", desc: "Library checkout sentinel" },
  { id: "rooftop.wind_fence_stress", tier: "tower-b", desc: "Wind fence sentinel" },
  { id: "infinity.pool_edge_pressure", tier: "tower-b", desc: "Pool edge sentinel" },
  { id: "sand.volume_replenish", tier: "service", desc: "Volleyball sand sentinel" },
  { id: "trailhead.signage_miss", tier: "service", desc: "Trail signage sentinel" },
  { id: "ski.gear_inventory_gap", tier: "tower-a", desc: "Ski concierge inventory sentinel (demo placeholder)" },
  { id: "golf.cart_battery_health", tier: "service", desc: "Golf cart battery sentinel (demo placeholder)" },
  { id: "marina.berth_conflict", tier: "tower-b", desc: "Berth conflict sentinel" },
  { id: "submarine.tour_delay_min", tier: "tower-b", desc: "Underwater tour delay sentinel (demo placeholder)" },
  { id: "observatory.cloud_cover_proxy", tier: "tower-b", desc: "Observatory cloud proxy sentinel" },
  { id: "telescope.tracking_jitter", tier: "tower-b", desc: "Telescope jitter sentinel" },
  { id: "starlink.handover_drop_pct", tier: "service", desc: "Satellite handover sentinel" },
  { id: "mesh.backhaul_flap", tier: "service", desc: "Mesh flap sentinel" },
  { id: "iot.firmware_skew_pct", tier: "service", desc: "Firmware skew sentinel" },
  { id: "zigbee.channel_noise", tier: "tower-a", desc: "Zigbee noise sentinel" },
  { id: "thread.border_router_reset", tier: "tower-b", desc: "Thread router reset sentinel" },
  { id: "matter.commission_timeout", tier: "tower-a", desc: "Matter commission timeout sentinel" },
  { id: "ble.proximity_spam", tier: "lobby", desc: "BLE proximity spam sentinel" },
  { id: "nfc.replay_attempts", tier: "lobby", desc: "NFC replay sentinel" },
  { id: "qr.deep_link_fail_pct", tier: "lobby", desc: "QR deep link sentinel" },
  { id: "calendar.sync_skew_min", tier: "backoffice", desc: "Calendar sync skew sentinel" },
  { id: "rooming.list_collision", tier: "backoffice", desc: "Rooming list collision sentinel" },
  { id: "share.block_overcommit_pct", tier: "backoffice", desc: "Block overcommit sentinel" },
  { id: "wash.hold_pattern_skew", tier: "backoffice", desc: "Wash pattern sentinel" },
  { id: "barter.comp_set_blindspot", tier: "backoffice", desc: "Comp blindspot sentinel" },
  { id: "walk.report_freshness_h", tier: "backoffice", desc: "Walk report freshness sentinel" },
  { id: "revpar.lift_bridge_gap", tier: "backoffice", desc: "RevPAR bridge sentinel" },
  { id: "gop.par_margin_variance", tier: "backoffice", desc: "GOP parity sentinel" },
  { id: "labor.hours_variance_pct", tier: "service", desc: "Labor mix sentinel" },
  { id: "break.shift_swap_noise", tier: "service", desc: "Shift swap sentinel" },
  { id: "tips.pool_distribution_skew", tier: "tower-a", desc: "Tip pool skew sentinel" },
  { id: "union.rule_collision_flag", tier: "service", desc: "Rule collision sentinel" },
  { id: "trainer.cert_expiry_pressure", tier: "service", desc: "Cert expiry sentinel" },
  { id: "vendor.po_ack_lag_h", tier: "backoffice", desc: "PO ack lag sentinel" },
  { id: "invoice.three_way_mismatch_pct", tier: "backoffice", desc: "Three-way sentinel" },
  { id: "rebate.program_drift_pct", tier: "backoffice", desc: "Rebate drift sentinel" },
  { id: "escrow.release_block_min", tier: "backoffice", desc: "Escrow release sentinel" },
  { id: "legal.hold_queue_depth", tier: "backoffice", desc: "Legal hold sentinel" },
  { id: "gdpr.erase_request_lag_h", tier: "backoffice", desc: "GDPR erase lag sentinel" },
  { id: "pci.scan_gaps_days", tier: "backoffice", desc: "PCI scan gap sentinel" },
  { id: "soc2.evidence_stale_days", tier: "backoffice", desc: "Evidence staleness sentinel" },
  { id: "hipaa.phi_touchpoints", tier: "backoffice", desc: "PHI touchpoint sentinel" },
  { id: "sox.journal_spike", tier: "backoffice", desc: "Journal spike sentinel" },
  { id: "insurance.claim_open_days", tier: "backoffice", desc: "Claim open sentinel" },
  { id: "tax.lodging_audit_flag", tier: "backoffice", desc: "Lodging tax audit sentinel" },
  { id: "carbon.intensity_proxy_kg", tier: "service", desc: "Carbon proxy sentinel" },
  { id: "water.usage_spike_pct", tier: "service", desc: "Water spike sentinel" },
  { id: "waste.diversion_variance", tier: "service", desc: "Waste diversion sentinel" },
  { id: "food.waste_kg_per_cover", tier: "service", desc: "Food waste sentinel" },
  { id: "menu.allergen_label_miss", tier: "service", desc: "Allergen label sentinel" },
  { id: "buffet.hot_hold_variance_c", tier: "tower-a", desc: "Hot hold sentinel" },
  { id: "barcode.scan_dup_ratio", tier: "lobby", desc: "Scan duplicate sentinel" },
  { id: "coupon.redemption_velocity", tier: "lobby", desc: "Coupon velocity sentinel" },
  { id: "giftcard.float_variance", tier: "lobby", desc: "Gift card float sentinel" },
  { id: "voucher.fraud_lift_pts", tier: "lobby", desc: "Voucher fraud sentinel" },
  { id: "identity.doc_liveness_miss_pct", tier: "lobby", desc: "Doc liveness sentinel" },
  { id: "biometric.false_reject_pct", tier: "lobby", desc: "Biometric FRR sentinel" },
  { id: "age_gating.soft_block_ratio", tier: "tower-b", desc: "Age gating sentinel" },
  { id: "localization.fallback_burst", tier: "service", desc: "i18n fallback sentinel" },
  { id: "timezone.dst_skew_seconds", tier: "backoffice", desc: "DST skew sentinel" },
  { id: "currencyRounding.variance_sat", tier: "backoffice", desc: "Rounding variance sentinel" },
  { id: "loyalty.fx_points_drift_pts", tier: "backoffice", desc: "Points FX sentinel" },
  { id: "survey.nps_sampling_bias", tier: "tower-a", desc: "NPS bias sentinel" },
  { id: "review.fake_cluster_score", tier: "tower-b", desc: "Review cluster sentinel" },
  { id: "rating.platform_divergence_stars", tier: "tower-b", desc: "Rating divergence sentinel" },
  { id: "complaint.topic_model_drift", tier: "backoffice", desc: "Topic drift sentinel" },
  { id: "social.mention_velocity_spike", tier: "backoffice", desc: "Mention spike sentinel" },
  { id: "influencer.contract_sla_h", tier: "backoffice", desc: "Influencer SLA sentinel" },
  { id: "brand.guideline_violation_pct", tier: "backoffice", desc: "Brand violation sentinel" },
  { id: "photo.asset_rights_expiry_d", tier: "backoffice", desc: "Asset rights sentinel" },
  { id: "drone.patrol_dropouts", tier: "service", desc: "Drone patrol sentinel" },
  { id: "robot.vacuum_stall_min", tier: "service", desc: "Robot vacuum stall sentinel" },
  { id: "amr.elev_hitch_delay_sec", tier: "service", desc: "AMR elevator hitch sentinel" },
  { id: "llm.hallucination_guard_fail_pct", tier: "backoffice", desc: "LLM guardrail sentinel" },
  { id: "rag.citation_miss_ratio", tier: "backoffice", desc: "RAG citation sentinel" },
  { id: "agent.tool_timeout_ms", tier: "service", desc: "Agent tool timeout sentinel" },
  { id: "eval.dataset_skew_score", tier: "backoffice", desc: "Eval skew sentinel" },
  { id: "shadow.traffic_split_drift", tier: "service", desc: "Shadow traffic drift sentinel" },
  { id: "chaos.experiment_stall", tier: "service", desc: "Chaos stall sentinel" },
  { id: "postmortem.action_item_age_d", tier: "backoffice", desc: "Postmortem aging sentinel" },
  { id: "oncall.page_noise_ratio", tier: "service", desc: "Page noise sentinel" },
  { id: "handover.doc_stale_h", tier: "service", desc: "Handover doc staleness sentinel" },
  { id: "runbook.link_rot_pct", tier: "service", desc: "Runbook rot sentinel" },
  { id: "wiki.search_zero_result_pct", tier: "service", desc: "Wiki zero sentinel" },
  { id: "confluence.duplicate_burst", tier: "service", desc: "Doc duplicate sentinel" },
  { id: "jira.cross_team_cycle_days", tier: "backoffice", desc: "Jira cycle sentinel" },
  { id: "github.pr_review_lag_h", tier: "backoffice", desc: "PR review lag sentinel" },
  { id: "ci.pipeline_flake_pct", tier: "service", desc: "CI flake sentinel" },
  { id: "cd.rollout_undo_ratio", tier: "service", desc: "Deploy undo sentinel" },
  { id: "sbom.license_risk_pts", tier: "backoffice", desc: "SBOM risk sentinel" },
  { id: "supply_chain.cve_pressure", tier: "backoffice", desc: "CVE pressure sentinel" },
  { id: "secret.scan_miss_ratio", tier: "service", desc: "Secret scan sentinel" },
  { id: "dependabot.queue_depth", tier: "service", desc: "Dependency queue sentinel" }
]);

module.exports = { TELEMETRY_LABELS: LABELS, telemetryLabelCount: () => LABELS.length };
